### ISSUE TITLE
Поддержка билдов x64 и netcore

### ISSUE THREAD

**Issue by EvilBeaver** [otymko/OneScript.WebSite#17]
Связано с https://github.com/EvilBeaver/OneScript/issues/784

Требуется: Обеспечить, чтобы бэкенд сайта умел различать релизы x64 и в перспективе - netcore

**Comment by otymko** [comment]
Нужно знать какая будет маска у файлов.

**Comment by EvilBeaver** [comment]
я уже начал эту задачу, так что на меня назначу

**Comment by EvilBeaver** [comment]
netcore пусть будет отдельно. А эту закроем
