### ISSUE TITLE
Убрать PayPal со страницы донатов

### ISSUE THREAD

**Issue by EvilBeaver** [otymko/OneScript.WebSite#30]
https://oscript.io/dev/contribute для yoomoney не работает, а paypal хоть и работает, но не для РФ.

Нужно обновить страницу контрибьюта, лучше всего дать ссылку на донаты Веселого1С https://donate.stream/openbsl-foundation

**Comment by zeegin** [comment]
В тиньков можно просто счет создать для донатов и разместить код получения

**Comment by JohnyDeath** [comment]
И вставить эту ссылку на донат на главную страницу. В "контрибютинг" переходят единицы
