### ISSUE TITLE
Состав подвала сайта

### ISSUE THREAD

**Issue by otymko** [otymko/OneScript.WebSite#6]
Определить состав блоков подвала сайта
![image](https://user-images.githubusercontent.com/11651847/56775949-bac99e00-67f3-11e9-9881-b23147c1f1b5.png)

**Comment by EvilBeaver** [comment]
На скриншоте - идеально. Что еще определять?

**Comment by otymko** [comment]
@EvilBeaver Так это же моя только точка зрения. Давай оставим как есть
